### ISSUE TITLE
leave more steps as exercises

### ISSUE THREAD

**Issue by wikfeldt** [coderefinery/mma#32]
it's difficult to listen to an instructor perform steps (create directories, paste code into files, compiling etc) and have time to type on own laptop at the same time. The instructions are usually clear and could be left to the learners (using stickies as usual)

**Comment by blindij** [comment]
I agree with your comment. Second half of the lesson was smoother as Radovan let people type.

**Comment by bast** [comment]
:+1: exercises give some air to teachers and prevent people from disconnecting.

**Comment by bast** [comment]
I have rewritten and simplified the pybind11 example. Instead of the soundex algorithm (good idea but complex) I am now using a simple pet class. It is otherwise difficult to explain soundex in 2 minutes. And since it is almost impossible, people will try to exercise on an example that they do not understand. "Only confuse people with one new idea at a time - make examples that illustrate only one new point." (Joe Armstrong). Now it is hopefully simpler. Sorry for removing a lot of Bjoern's work but it was not wasted since it paved the way. Of course feel free to revert my stuff here but I am trying to simplify it to the essence: pybind11.
